#!/bin/bash
# dkeger -- choose from a bunch of sexy Xresources
feh --montage --thumbnails /home/$USER/.colors/*.png &
echo "Which theme to use?"
dir /home/$USER/.colors
TMPFILE=/tmp/dkeger_store
touch $TMPFILE
XRSREAL=/home/$USER/.Xresources
XRSFAKE=/home/$USER/.Xresources_new
SELECTED=/home/$USER/.colors/$THEME
FULLNAME=("#include <${SELECTED}>")
sed '/include/d' < $XRSREAL > $TMPFILE
mv $TMPFILE $XRSREAL
echo -e ${FULLNAME} >> $XRSREAL
echo "$XRSREAL written..."
xrdb -merge $XRSREAL
echo "$XRSREAL merged..."
echo "You can close this terminal now."
setsid x-terminal-emulator
exit 0