#!/bin/bash
# takes an image and creates a color palette from it
# which gets echoed to the console.
#
# made by rhowaldt (fuck you)
#
# depends: imagemagick

PALETTE=$(convert "$1" -colors 16 -format "%c" histogram:info:)
HEXLIST=$(echo "$PALETTE" | sed 's/^.*\#\(.*\) srgb.*/\1/g')
COL=("0" "8" "1" "9" "2" "A" "3" "B" "4" "C" "5" "D" "6" "E" "7" "F");
CLEAN=$(echo $COL | sed 's/^0*//')

x=0

## Since using the generic bg/fg, just pop it right in
echo "!!!! <$SELECT> !!!!"
echo "*background:"'#'"170f0d"
echo "*foreground:"'#'"746c48"
echo "*fading:10"
echo "*fadeColor:"'#'"170f0d"
echo "*transparent:0"
echo "*shading:70"

## Get the ouput of the color palette
while read -r line; do
    [[ "$line" ]] || continue
    echo -en *color$x: '#'"${CLEAN}$line\n";
    x=$((x+1))
done < <(convert "$1" -colors 16 -format "%c" histogram:info: | sed 's/^.*\#\(.*\) srgb.*/\1/g')
